Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-05, with the labels that each got.

#127 fix: we can use Max Squish in PhysBone 1.0
  CHANGELOG-PRERELEASE.md
  Editor/MergePhysBoneEditor.cs
Labels: NO-CHANGELOG

#131 docs(readme): update link to installer
  README.md
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#140 ci: fix hugo version
  .github/workflows/release.yml
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#141 ci: fix clone submodules correctly
  .github/workflows/release.yml
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#143 Hugo docs improvements
  .docs/config.toml
  .docs/content/_index.ja.md
  .docs/content/_index.md
Labels: documentation, NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#144 ci: allow no changelog changes in documentation pull request
  .github/workflows/changelog-check.yml
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#148 docs: remove most parts from README and link to official site
  .readme/clear-endpoint-position.png
  .readme/freeze-blend-shape.png
  .readme/make-children.png
  .readme/merge-bone.png
  .readme/merge-physbone.png
  .readme/merge-skinned-mesh.png
  .readme/merge-toon-lit-material.png
  .readme/remove-mesh-in-box.example.pre.png
  .readme/remove-mesh-in-box.example.ran.png
  .readme/remove-mesh-in-box.gizmo.png
  .readme/remove-mesh-in-box.png
  .readme/unused-bones-by-references-tool.png
  README.md
Labels: documentation

#149 Fix hugo docs version
  .docs/config.toml
  .github/workflows/release.yml
Labels: documentation

#150 chore: update link to ja page
  README.md
Labels: documentation

#151 docs: re-capture components
  .docs/README.md
  .docs/content/docs/reference/clear-endpoint-position/component.png
  .docs/content/docs/reference/clear-endpoint-position/index.md
  .docs/content/docs/reference/freeze-blendshape/component.png
  .docs/content/docs/reference/freeze-blendshape/index.md
  .docs/content/docs/reference/make-children/component.png
  .docs/content/docs/reference/make-children/index.md
  .docs/content/docs/reference/merge-bone/component.png
  .docs/content/docs/reference/merge-bone/index.md
  .docs/content/docs/reference/merge-physbone/component.png
  .docs/content/docs/reference/merge-physbone/index.md
  .docs/content/docs/reference/merge-skinned-mesh/component.png
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  .docs/content/docs/reference/merge-toonlit-material/component.png
  .docs/content/docs/reference/merge-toonlit-material/index.md
  .docs/content/docs/reference/remove-mesh-in-box/component.png
  .docs/content/docs/reference/remove-mesh-in-box/index.md
  .docs/content/docs/reference/unused-bones-by-references-tool/component.png
  .docs/content/docs/reference/unused-bones-by-references-tool/index.md
Labels: documentation

#167 fix: error when we opened Editor of MergePhysBone
  CHANGELOG-PRERELEASE.md
  Editor/MergePhysBoneEditor.cs
Labels: NO-CHANGELOG

#171 fix: returns true with null for non-components in MapComponentInstance
  Editor/ObjectMapping/ObjectMapping.cs
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#176 Errors in object mapping
  CHANGELOG-PRERELEASE.md
  Editor/ObjectMapping/AnimationObjectMapper.cs
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Test~/ObjectMappingTest.cs
Labels: NO-CHANGELOG

#175 docs: fix mistake
  .docs/content/docs/reference/make-children/index.md
  .docs/content/docs/reference/merge-bone/index.md
  .docs/content/docs/reference/merge-physbone/index.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  .docs/content/docs/reference/merge-toonlit-material/index.md
  .docs/content/docs/reference/remove-mesh-in-box/index.md
Labels: documentation

#174 fix: Japanese translation
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Localization/ja.po
Labels: NO-COMMIT-CHECK

#187 docs: add Japanese documentation
  .docs/content/_index.ja.md
  .docs/content/docs/reference/_index.ja.md
  .docs/content/docs/reference/clear-endpoint-position/index.ja.md
  .docs/content/docs/reference/freeze-blendshape/index.ja.md
  .docs/content/docs/reference/make-children/index.ja.md
  .docs/content/docs/reference/merge-bone/index.ja.md
  .docs/content/docs/reference/merge-physbone/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-toonlit-material/index.ja.md
  .docs/content/docs/reference/remove-mesh-in-box/index.ja.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.ja.md
Labels: documentation

#189 ci: re-run changelog/commit checks on label events
  .github/workflows/changelog-check.yml
  .github/workflows/conventionalcommits.yml
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#191 docs(merge-skinned-mesh): improve suggesting freezing blendshapes
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
Labels: documentation

#192 fix missing localizations
  Editor/MergePhysBoneEditor.cs
  Internal/PrefabSafeSet/Editor/PrefabSafeSetEditor.cs
  Localization/en.po
  Localization/ja.po
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE
