Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-08, with the labels that each got.

#279 fix: parsing animation
  Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.FindUnusedObjects.cs
Labels: NO-CHANGELOG

#275 feat: add remove mesh by blend shape component
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditSkinnedMeshComponentUtil.cs
  Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs.meta
  Editor/RemoveMeshByBlendShapeEditor.cs
  Editor/RemoveMeshByBlendShapeEditor.cs.meta
  Localization/en.po
  Localization/ja.po
  Runtime/RemoveMeshByBlendShape.cs
  Runtime/RemoveMeshByBlendShape.cs.meta
Labels: NO-COMMIT-CHECK

#283 Remove mesh by blend shape
  .docs/content/docs/reference/remove-mesh-by-blendshape/component.png
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditSkinnedMeshComponentUtil.cs
  Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs.meta
  Editor/RemoveMeshByBlendShapeEditor.cs
  Editor/RemoveMeshByBlendShapeEditor.cs.meta
  Localization/en.po
  Localization/ja.po
  Runtime/RemoveMeshByBlendShape.cs
  Runtime/RemoveMeshByBlendShape.cs.meta
Labels: NO-COMMIT-CHECK

#298 chore: add warning about executeEarly
  Editor/MakeChildrenEditor.cs
  Localization/en.po
  Localization/ja.po
Labels: NO-CHANGELOG

#300 docs(tutorial): refine japanese tutorial
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation

#307 chore: add unity file used in tutorial
  .docs/Anon.unity
Labels: NO-CHANGELOG

#318 chore: do not add GlobalActivator if there are no avatars in the scene
  CHANGELOG-PRERELEASE.md
  Internal/ApplyOnPlay/Editor/ApplyOnPlayCaller.cs
  Internal/ApplyOnPlay/Runtime/ApplyOnPlayActivator.cs
  Internal/ApplyOnPlay/Runtime/GlobalActivator.cs
  Internal/ApplyOnPlay/Runtime/SceneChangeReceiver.cs
  Internal/ApplyOnPlay/Runtime/SceneChangeReceiver.cs.meta
  Internal/ApplyOnPlay/Runtime/com.anatawa12.avatar-optimizer.internal.apply-on-play.runtime.asmdef
Labels: SNAPSHOT-ONLY

#332 fix(trace-and-optimize): something are not considered
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.CollectUsages.cs
  Editor/Utils.cs
Labels: bug

#327 docs: add about component kinds and where should be added
  .docs/content/docs/component-kind/_index.ja.md
  .docs/content/docs/component-kind/_index.md
  .docs/content/docs/component-kind/avatar-global-components/index.ja.md
  .docs/content/docs/component-kind/avatar-global-components/index.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.md
  .docs/content/docs/reference/_index.ja.md
  .docs/content/docs/reference/_index.md
  .docs/content/docs/reference/clear-endpoint-position/index.ja.md
  .docs/content/docs/reference/clear-endpoint-position/index.md
  .docs/content/docs/reference/freeze-blendshape/index.ja.md
  .docs/content/docs/reference/freeze-blendshape/index.md
  .docs/content/docs/reference/make-children/index.ja.md
  .docs/content/docs/reference/make-children/index.md
  .docs/content/docs/reference/merge-bone/index.ja.md
  .docs/content/docs/reference/merge-bone/index.md
  .docs/content/docs/reference/merge-physbone/index.ja.md
  .docs/content/docs/reference/merge-physbone/index.md
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  .docs/content/docs/reference/merge-toonlit-material/index.ja.md
  .docs/content/docs/reference/merge-toonlit-material/index.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/remove-mesh-in-box/index.ja.md
  .docs/content/docs/reference/remove-mesh-in-box/index.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.ja.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.md
Labels: documentation

#348 fix: no error context in Multi Pass Rendering error
  CHANGELOG-PRERELEASE.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: SNAPSHOT-ONLY

#349 chore: Japanese translation of weight mismatch warning
  Localization/ja.po
Labels: NO-CHANGELOG

#350 docs: fix link from component kind to components
  .docs/content/docs/component-kind/avatar-global-components/index.ja.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
Labels: documentation

#355 docs(ja): change wording of "developing avatars" in clear-endpoint-position
  .docs/content/docs/reference/clear-endpoint-position/index.ja.md
Labels: documentation, localization

#360 ci: add check to prevent feature release in patch release branch
  .github/workflows/changelog-check.yml
  .github/workflows/prevent-merging-feature.yml
Labels: ci

#361 Trace and optimize process refactor
  Editor/Processors/AutomaticConfiguration/AutomaticConfigurationProcessor.CollectUsages.cs
  Editor/Processors/AutomaticConfiguration/TraceAndOptimizeProcessor.cs
  Editor/Processors/TraceAndOptimize.meta
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs.meta
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs.meta
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs.meta
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs.meta
  Editor/Utils.cs
Labels: refactor

#366 docs(ja): マージ to 統合
  .docs/content/docs/tutorial/basic-usage/index.ja.md
Labels: documentation, localization

#369 chore: next version is 1.4.0
  package.json
Labels: enhancement, NO-CHANGELOG

#370 fix: auto freeze meaningless blendshape is after freeze blendshape
  Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
Labels: NO-CHANGELOG

#372 build: exclude test folder from distribution package
  .github/workflows/release.yml
Labels: ci

#379 Merge bone for non restpose
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Math.meta
  Editor/Math/Matrix4x4.cs
  Editor/Math/Matrix4x4.cs.meta
  Editor/Processors/EditSkinnedMeshComponentProcessor.cs
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Editor/Utils.cs
Labels: bug, enhancement

#381 Better error for meshinfo2 error
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/EditSkinnedMeshComponentProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Internal/ErrorReporter/Editor/BuildReport.cs
Labels: problem

#383 refactor: remove unused methods Utils
  Editor/Utils.cs
Labels: refactor

#384 Support multi pass rendering
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: enhancement

#391 chore(ja): "Blend Shape" to "BlendShape"
  Localization/ja.po
Labels: localization

#389 feat(remove-mesh-by-blendshape/editor): auto set blendshape weight
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/RemoveMeshByBlendShapeEditor.cs
  Localization/en.po
  Localization/ja.po
Labels: enhancement

#396 ci: add support for improvement label
  .github/workflows/prevent-merging-feature.yml
Labels: ci
