Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-12, with the labels that each got.

#781 docs(chagelog): use - instad of *
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
Labels: documentation

#782 fix error when editing prefab in 2022
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
Labels: bug

#784 Fix remove mesh in box inspector
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/RemoveMeshInBoxEditor.cs
Labels: bug

#786 Warning instead of IndexOutOfBoundsException
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/AnimatorParsers/AnimatorParser.cs
  Editor/OptimizerPlugin.cs
  Editor/Processors/ParseAnimator.cs
  Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs
  Editor/Processors/TraceAndOptimize/OptimizePhysBone.cs.meta
  Localization/en.po
  Localization/ja.po
  Test~/EnumValues.cs
  Test~/EnumValues.cs.meta
Labels: improvement

#787 Support VRCSDK 3.5.0
  .github/workflows/gameci.yml
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  package.json
Labels: improvement

#789 ci: install package manually for now
  .github/workflows/gameci.yml
Labels: ci

#791 ci: revert manual installation of dependencies
  .github/workflows/gameci.yml
Labels: ci

#794 fix: error with generic avatar in 2022
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.cs
Labels: bug

#802 Fix VRM component definitions
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.VRM0.cs
  Editor/APIInternal/ComponentInfos.VRM1.cs
Labels: bug

#806 ci: add bd_ prerelease repository for ndmf prereleases
  .github/workflows/gameci.yml
Labels: ci

#808 Fix: Object mapping did not work
  CHANGELOG-PRERELEASE.md
  Editor/ObjectMapping/ObjectMappingContext.cs
Labels: SNAPSHOT-ONLY
