Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-09, with the labels that each got.

#398 chore: make human readable error when we found missing script component
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/OptimizerProcessor.cs
Labels: improvement

#399 Fix RootBone become None
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Test~/MeshInfo2/MeshInfo2Test.cs
Labels: bug

#400 chore: Just rethrow exception if not in error reporting scope
  Internal/ErrorReporter/Editor/BuildReport.cs
Labels: NO-CHANGELOG, improvement

#403 fix: GetConstantValue returns false if variable
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
Labels: bug

#401 Better Remove Unused Objects: GC Objects
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ExternalLibraryAccessor.cs
  Editor/ExternalLibraryAccessor.cs.meta
  Editor/OptimizerProcessor.cs
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs.meta
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Labels: enhancement

#404 fix: Animator Component is a entrypoint
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#405 fix: MeshFilter disappears
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#407 fix: PipelineSaver disappears
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#408 fix: blendshape with weight at zero
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Test~/MeshInfo2/MeshInfo2Test.cs
  Test~/MeshInfo2/single-0.asset
  Test~/MeshInfo2/single-0.asset.meta
Labels: bug

#409 merge 1.4.3
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Test~/MeshInfo2/MeshInfo2Test.cs
  Test~/MeshInfo2/single-0.asset
  Test~/MeshInfo2/single-0.asset.meta
Labels: bug, SNAPSHOT-ONLY

#410 fix: warning message of Unknown Type is not localized
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Localization/en.po
  Localization/ja.po
Labels: SNAPSHOT-ONLY, localization

#421 Share MeshInfo2 globally
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/OptimizerProcessor.cs
  Editor/OptimizerSession.cs
  Editor/Processors/EditSkinnedMeshComponentProcessor.cs
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/MeshInfo2Holder.cs.meta
  Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs
Labels: refactor

#423 fix: Unity 2022 crash workaround
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Localization/AssemblyInfo.cs
  Localization/AssemblyInfo.cs.meta
  Localization/com.anatawa12.avatar-optimizer.localization.asmdef
  Localization/com.anatawa12.avatar-optimizer.localization.asmdef.meta
Labels: bug

#417 Merge bone validation
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
  Internal/ErrorReporter/Editor/ComponentValidation.cs
  Localization/en.po
  Localization/ja.po
  Runtime/MergeBone.cs
Labels: improvement

#418 Validation error for self recursive MergeSkinnedMesh
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/MergeSkinnedMeshEditor.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Localization/en.po
  Localization/ja.po
Labels: improvement

#419 Exclude from Trace and Optimize
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/AutomaticConfiguration.cs
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Localization/en.po
  Localization/ja.po
  Runtime/TraceAndOptimize.cs
Labels: enhancement

#427 fix: unknown type warning is not correctly rendered
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#426 fix: MergeBone with uneven scale is supported if all children are merged
  CHANGELOG-PRERELEASE.md
  Editor/Processors/MergeBoneProcessor.cs
  Localization/en.po
  Localization/ja.po
Labels: bug, SNAPSHOT-ONLY

#431 fix: MakeChildren become unknown-type of TraceAndOptimize
  CHANGELOG-PRERELEASE.md
  Editor/Processors/MakeChildrenProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#433 Auto merge bone
  CHANGELOG-PRERELEASE.md
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Editor/OptimizerProcessor.cs
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Runtime/TraceAndOptimize.cs
Labels: enhancement, SNAPSHOT-ONLY, area-TraceAndOptimize

#430 Migrate from unused bones by reference
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.ja.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/AutomaticConfiguration.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Editor/UnusedBonesByReferencesToolEditor.cs
  Editor/UnusedBonesByReferencesToolEditor.cs.meta
  Localization/en.po
  Localization/ja.po
  Runtime/TraceAndOptimize.cs
  Runtime/UnusedBonesByReferencesTool.cs
Labels: enhancement

#435 chore(ja): Code review that was late for #430 merge
  Localization/ja.po
Labels: localization

#438 ContactBase is accidentally erased by Remove unsed Objects Automatically.
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#440 fix: broken if there are BlendShapes without moving vertices
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: bug

#441 GC parent inactive
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#442 fix: NRE
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, NO-CHANGELOG

#448 fix: MergeBone will break normal and tangent
  CHANGELOG-PRERELEASE.md
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#452 fix: PB for Animator Parameter disappears
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY, area-TraceAndOptimize

#454 Fix auto merge bone ignores active animation
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug

#456 fix: Error if we merge bone recursively
  CHANGELOG-PRERELEASE.md
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#457 fix: tangent broken with merge bone
  CHANGELOG-PRERELEASE.md
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#461 fix: Transform animation broken
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#463 fix: Collider disappears
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug, SNAPSHOT-ONLY

#465 fix: Behaviour can disappears if initially disabled
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#464 feat: add components for gc debug
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Runtime/TraceAndOptimize.cs
Labels: enhancement

#467 Avoid Name Conflict in MergeBone
  .docs/content/docs/reference/merge-bone/component.png
  .docs/content/docs/reference/merge-bone/index.ja.md
  .docs/content/docs/reference/merge-bone/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Localization/en.po
  Localization/ja.po
  Runtime/MergeBone.cs
Labels: bug, enhancement

#468 docs: add Contributing Guide
  CONTRIBUTING.md
  CONTRIBUTING.md.meta
Labels: documentation

#473 fix: StaticRenderer is not removed
  CHANGELOG-PRERELEASE.md
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#476 chore: automatically merge unnecessary activeness animated GameObject
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: enhancement, SNAPSHOT-ONLY, area-TraceAndOptimize

#477 chore: update screenshot of merge bone
  .docs/content/docs/reference/merge-bone/component.png
Labels: documentation

#484 chore: fix some expression
  .docs/content/docs/tutorial/basic-usage/index.ja.md
Labels: documentation, localization

#487 fix(animator-parser): eyelids with bone is not considered
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
Labels: bug, SNAPSHOT-ONLY

#479 docs(tutorial/ja): add T&O at top and add remove mesh with blendshape
  .docs/Anon.unity
  .docs/README.md
  .docs/content/docs/tutorial/basic-usage/add-freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
  .docs/content/docs/tutorial/basic-usage/remove-mesh-by-blendshape.png
Labels: documentation

#490 chore: nor to or
  CONTRIBUTING.md
Labels: documentation, NO-CHANGELOG, NO-COMMIT-CHECK

#493 fix: left eye disappears
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
Labels: bug, SNAPSHOT-ONLY

#494 fix(docs): image link miss
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation

#495 fix: MergeBone may lost position information with extreamly small object
  CHANGELOG-PRERELEASE.md
  Editor/Math/Matrix4x4.cs
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#496 fix: manually configured MergeBone is removed by GC Objects
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#498 chore: remove unused bone references just after reading mesh
  CHANGELOG-PRERELEASE.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: enhancement, SNAPSHOT-ONLY

#489 Remove mesh components EditMode preview
  Editor/EditModePreview.meta
  Editor/EditModePreview/BlendShapePreviewContext.cs
  Editor/EditModePreview/BlendShapePreviewContext.cs.meta
  Editor/EditModePreview/MeshPreviewController.cs
  Editor/EditModePreview/MeshPreviewController.cs.meta
  Editor/EditModePreview/RemoveMeshByBlendShapePreviewContext.cs
  Editor/EditModePreview/RemoveMeshByBlendShapePreviewContext.cs.meta
  Editor/EditModePreview/RemoveMeshPreviewController.cs
  Editor/EditModePreview/RemoveMeshPreviewController.cs.meta
  Editor/EditModePreview/RemoveMeshWithBoxPreviewContext.cs
  Editor/EditModePreview/RemoveMeshWithBoxPreviewContext.cs.meta
  Editor/RemoveMeshByBlendShapeEditor.cs
  Editor/RemoveMeshInBoxEditor.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Runtime/RemoveMeshInBox.cs
  Runtime/com.anatawa12.avatar-optimizer.runtime.asmdef
Labels: enhancement

#499 fix: rotation and lossy scale
  CHANGELOG-PRERELEASE.md
  Editor/Math/Matrix3x3.cs
  Editor/Math/Matrix3x3.cs.meta
  Editor/Math/Matrix4x4.cs
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#502 fix: AvatarMask is not mapped
  CHANGELOG-PRERELEASE.md
  Editor/ObjectMapping/AnimationObjectMapper.cs
  Editor/Processors/ApplyObjectMapping.cs
Labels: bug, SNAPSHOT-ONLY

#503 docs(changelog): Full EditMode Preview of RemoveMesh Components in rc.5
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
Labels: documentation

#375 feat: Initial integration with NDMF
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/OptimizerProcessor.cs
  Editor/OptimizerSession.cs
  Editor/Processors/OptimizerPlugin.cs
  Editor/Processors/OptimizerPlugin.cs.meta
  Editor/Utils.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Internal/ApplyOnPlay/Editor/ApplyOnPlayCallbackRegistry.cs
  Internal/ApplyOnPlay/Editor/ApplyOnPlayCaller.cs
  Internal/ApplyOnPlay/Editor/ApplyOnPlayConfiguration.cs
  Internal/ApplyOnPlay/Editor/IApplyOnPlayCallback.cs
  Internal/ApplyOnPlay/Editor/ManualBake.cs
  Internal/ApplyOnPlay/Editor/ManualBakeFinallizer.cs
  Internal/ApplyOnPlay/Editor/RemoveEditorOnlyOnPlay.cs
  Internal/ApplyOnPlay/Editor/com.anatawa12.avatar-optimizer.internal.apply-on-play.editor.asmdef
  Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs
  Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef
Labels: enhancement

#511 Error reporting on ndmf
  CHANGELOG-PRERELEASE.md
  Editor/Processors/OptimizerPlugin.cs
  Internal/ErrorReporter/Editor/BuildReport.cs
  Internal/ErrorReporter/Editor/BuildReportContext.cs
  Internal/ErrorReporter/Editor/BuildReportContext.cs.meta
  Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs
  Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs.meta
  Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef
Labels: SNAPSHOT-ONLY

#512 fix: Some missing EntryPoint Components
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Labels: SNAPSHOT-ONLY

#509 feat: add warning for Modular Avatar 1.7.0 or older
  CHANGELOG-PRERELEASE.md
  Editor/LegacyModularAvatarWarning.cs
  Editor/LegacyModularAvatarWarning.cs.meta
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Localization/en.po
  Localization/ja.po
Labels: SNAPSHOT-ONLY

#513 chore: declare compatible with VRCSDK 3.4.x
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  package.json
Labels: enhancement

#515 test: add test for runtime build
  Test~/BuildAssetBundle.cs
  Test~/BuildAssetBundle.cs.meta
  Test~/Empty.prefab
  Test~/Empty.prefab.meta
Labels: ci

#516 chore: remove asset management system in the AAO
  Editor/OptimizerSession.cs
  Editor/Processors/ApplyObjectMapping.cs
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/OptimizerPlugin.cs
  Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Editor/Processors/TraceAndOptimize/AnimatorParserDebugWindow.cs
  Editor/Utils.cs
  Test~/MergePhysBoneTest.cs
Labels: refactor

#517 chore: initialize MeshInfo2 in constructor of OptimizerSession
  Editor/OptimizerSession.cs
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/OptimizerPlugin.cs
Labels: refactor

#518 chore: remake updating shared SkinnedMeshEditorSorter
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditSkinnedMeshComponentUtil.cs
  Runtime/EditSkinnedMeshComponent.cs
  Runtime/RuntimeUtil.cs
Labels: bug, refactor

#519 fix: deprecation warnings
  Editor/EditModePreview/RemoveMeshByBlendShapePreviewContext.cs
  Editor/Processors/UnusedBonesByReferencesToolEarlyProcessor.cs
  Editor/UnusedBonesByReferencesToolEditor.cs
Labels: refactor
