Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-06, with the labels that each got.

#202 chore: use anatawa12's commitlint
  .github/workflows/commitlint.yml
  .github/workflows/conventionalcommits.yml
  commitlint.config.js
  commitlint.config.js.meta
Labels: NO-CHANGELOG, NO-CHANGELOG-PRERELEASE

#203 Merge 0.4 changes
  .github/workflows/commitlint.yml
  .github/workflows/conventionalcommits.yml
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  commitlint.config.js
  commitlint.config.js.meta
Labels: NO-COMMIT-CHECK

#204 ci
  .github/workflows/changelog-check.yml
  .github/workflows/commitlint.yml
  .github/workflows/release.yml
Labels: NO-CHANGELOG

#206 Add release note to website
  .docs/content/docs/changelog.ja.md
  .docs/content/docs/changelog.md
  .docs/layouts/partials/changelog/CHANGELOG-PRERELEASE.md
  .docs/layouts/partials/changelog/CHANGELOG.md
  .docs/layouts/shortcodes/changelog.html
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
Labels: documentation

#207 Tutorial
  .docs/content/docs/tutorial/_index.ja.md
  .docs/content/docs/tutorial/basic-usage/add-freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/add-merge-skinned-mesh.png
  .docs/content/docs/tutorial/basic-usage/create-empty.png
  .docs/content/docs/tutorial/basic-usage/drag-and-drop.png
  .docs/content/docs/tutorial/basic-usage/freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/lock-inspector.png
  .docs/content/docs/tutorial/basic-usage/start.png
Labels: documentation

#211 チュートリアルのタイポ修正
  .docs/content/docs/tutorial/basic-usage/index.ja.md
Labels: documentation, NO-COMMIT-CHECK

#212 Fix Typo
  .docs/content/docs/tutorial/basic-usage/index.ja.md
Labels: documentation, NO-COMMIT-CHECK

#213 Tutorial improvements
  .docs/content/docs/tutorial/basic-usage/add-freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/add-merge-skinned-mesh.png
  .docs/content/docs/tutorial/basic-usage/drag-and-drop.png
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/lock-inspector.png
Labels: documentation

#218 Merge 0.4
  .docs/content/docs/tutorial/basic-usage/add-freeze-blendshape.png
  .docs/content/docs/tutorial/basic-usage/add-merge-skinned-mesh.png
  .docs/content/docs/tutorial/basic-usage/drag-and-drop.png
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/lock-inspector.png
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/MergePhysBoneEditor.cs
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Internal/ErrorReporter/Editor/.generate.ts
  Internal/ErrorReporter/Editor/BuildReport.cs
  Internal/ErrorReporter/Editor/ErrorElement.cs
  Internal/ErrorReporter/Editor/ErrorLog.cs
  Internal/ErrorReporter/Editor/ErrorReportUI.cs
  Internal/ErrorReporter/Editor/Generated.cs
  Internal/ErrorReporter/Editor/Generated.cs.meta
  Internal/ErrorReporter/Editor/NominalException.cs
  Internal/ErrorReporter/Editor/NominalException.cs.meta
  Internal/ErrorReporter/Editor/Resources/com.anatawa12.avatar-optimizer.error-report.uss
  Internal/ErrorReporter/Editor/Utils.cs
  Internal/ErrorReporter/Editor/Utils.cs.meta
  Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef
  Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef.meta
  Internal/ErrorReporter/Runtime/ErrorReporterRuntime.cs
  Test~/ObjectMappingTest.cs
Labels: NO-COMMIT-CHECK

#232 docs: add FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, NO-CHANGELOG

#237 docs: add reference to actual performance window
  .docs/content/docs/tutorial/basic-usage/index.ja.md
Labels: documentation

#238 docs: add tutorial in english
  .docs/content/docs/tutorial/_index.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation

#241 docs: update installer unitypackage to 1.x.x
  .docs/content/_index.md
Labels: documentation

#243 chore: add notice about MA Logo
  .booth/README.md
Labels: NO-CHANGELOG

#244 Fix something for 1.0.0
  .docs/content/_index.ja.md
  .docs/content/_index.md
  Editor/DeleteGameObjectEditor.cs
  Editor/DeleteGameObjectEditor.cs.meta
  Editor/DummyObject.cs
  Editor/MaterialSaverUtility.cs
  Editor/MergeSkinnedMeshWindow.cs
  Editor/ShouldIgnoreComponentPatch.cs
  Internal/UnsafeUtils.meta
  Internal/UnsafeUtils/UtilsUsingUnsafe.cs
  Internal/UnsafeUtils/UtilsUsingUnsafe.cs.meta
  Internal/UnsafeUtils/assembly-info.cs
  Internal/UnsafeUtils/assembly-info.cs.meta
  Internal/UnsafeUtils/com.anatawa12.avatar-optimizer.internal.unsafe.asmdef
  Internal/UnsafeUtils/com.anatawa12.avatar-optimizer.internal.unsafe.asmdef.meta
  Runtime/Activator.cs
  Runtime/AvatarTagComponent.cs
  Runtime/DeleteGameObject.cs
  Runtime/DeleteGameObject.cs.meta
  Runtime/EditSkinnedMeshComponent.cs
  Runtime/MergePhysBone.cs
Labels: NO-CHANGELOG

#245 docs(readme): add about API stability
  README.md
Labels: documentation

#246 chore: improve zip
  .booth/zip/LICENSE.txt
  .booth/zip/README.en.txt
  .booth/zip/README.ja.txt
  .booth/zip/create.sh
Labels: NO-CHANGELOG
