Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-07, with the labels that each got.

#254 chore: update next version to 1.1.0
  package.json
Labels: NO-CHANGELOG

#255 Fix manual bake doesnt make assets
  CHANGELOG-PRERELEASE.md
  Editor/OptimizerProcessor.cs
  Editor/Utils.cs
  Internal/ApplyOnPlay/Editor/ApplyOnPlayCaller.cs
  Internal/ApplyOnPlay/Editor/IApplyOnPlayCallback.cs
  Internal/ApplyOnPlay/Editor/ManualBake.cs
  Internal/ApplyOnPlay/Editor/ModularAvatarSupport.cs
  Internal/ApplyOnPlay/Editor/RemoveEditorOnlyOnPlay.cs
  Internal/ErrorReporter/Editor/ErrorReportingInitializerProcessor.cs
Labels: SNAPSHOT-ONLY

#257 docs(changelog): improve about Completely rewrite apply on play system
  CHANGELOG.md
Labels: documentation

#258 Do not compress textures on play
  CHANGELOG-PRERELEASE.md
  Editor/OptimizerProcessor.cs
  Editor/OptimizerSession.cs
  Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
  Test~/MergePhysBoneTest.cs
Labels: SNAPSHOT-ONLY

#266 fix(docs): merge-bone index.ja.md
  .docs/content/docs/reference/merge-bone/index.ja.md
Labels: documentation

#268 Use Automatic Configuration in Tutorial
  .docs/content/docs/tutorial/basic-usage/add-automatic-configuration.png
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation

#270 chore: bump next version to 1.2.0 and revert 1.1.2-beta.1 release
  CHANGELOG-PRERELEASE.md
  package.json
Labels: NO-CHANGELOG
