Repository anatawa12/AvatarOptimizer, pull requests merged in 2023-10, with the labels that each got.

#526 docs: VPAIの記述をなくしてunitypackageインストールの説明をシンプルにする
  .docs/content/_index.ja.md
  .docs/content/_index.md
Labels: documentation

#527 fix: viseme may be broken
  CHANGELOG-PRERELEASE.md
  Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Runtime/InternalAutoFreezeMeaninglessBlendShape.cs
Labels: bug, SNAPSHOT-ONLY

#531 Docs image improvements
  .docs/content/docs/reference/merge-bone/component.png
  .docs/content/docs/tutorial/basic-usage/add-merge-skinned-mesh.png
Labels: documentation

#530 docs: some improvements
  .docs/content/_index.ja.md
  .docs/content/docs/component-kind/avatar-global-components/index.ja.md
  .docs/content/docs/component-kind/avatar-global-components/index.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.md
  .docs/content/docs/reference/_index.ja.md
  .docs/content/docs/reference/_index.md
  .docs/content/docs/reference/clear-endpoint-position/index.ja.md
  .docs/content/docs/reference/freeze-blendshape/index.ja.md
  .docs/content/docs/reference/merge-bone/index.ja.md
  .docs/content/docs/reference/merge-bone/index.md
  .docs/content/docs/reference/merge-physbone/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/tutorial/_index.ja.md
  .docs/content/docs/tutorial/_index.md
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation, NO-COMMIT-CHECK, localization

#535 docs/localization: 利点の説明を追加、その他改善
  .docs/content/docs/reference/freeze-blendshape/index.ja.md
  .docs/content/docs/reference/freeze-blendshape/index.md
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  .docs/content/docs/reference/merge-toonlit-material/index.ja.md
  .docs/content/docs/reference/merge-toonlit-material/index.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/remove-mesh-in-box/index.ja.md
  .docs/content/docs/reference/remove-mesh-in-box/index.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.ja.md
  .docs/content/docs/reference/unused-bones-by-references-tool/index.md
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Localization/ja.po
Labels: documentation, localization

#536 docs: missing option name of T&O
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
Labels: documentation

#540 hotfix: disable MergeBone BindPose optimization by default
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/DebugConfigWindow.cs
  Editor/DebugConfigWindow.cs.meta
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug

#541 fix: MergePhysBone component may remain with no sources
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergePhysBoneProcessor.cs
Labels: bug

#542 Fix merge bone break fur
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/DebugConfigWindow.cs
  Editor/DebugConfigWindow.cs.meta
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: bug

#543 pick gc debug
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: improvement

#546 fix: GC debug doesn't include inactive objects
  CHANGELOG-PRERELEASE.md
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
Labels: bug, SNAPSHOT-ONLY

#550 fix: EditMode Preview of RemoveMeshInBox is not correct
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/RemoveMeshPreviewController.cs
  Editor/EditModePreview/RemoveMeshWithBoxPreviewContext.cs
  Editor/Math/Matrix4x4.cs
Labels: bug

#551 chore: add NotKeyable to every components
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
  Runtime/AvatarTagComponent.cs
  Runtime/ClearEndpointPosition.cs
  Runtime/FreezeBlendShape.cs
  Runtime/InternalAutoFreezeMeaninglessBlendShape.cs
  Runtime/Legacy/Activator.cs
  Runtime/Legacy/GlobalActivator.cs
  Runtime/MakeChildren.cs
  Runtime/MergeBone.cs
  Runtime/MergePhysBone.cs
  Runtime/MergeSkinnedMesh.cs
  Runtime/MergeToonLitMaterial.cs
  Runtime/TraceAndOptimize.cs
  Runtime/UnusedBonesByReferencesTool.cs
  Test~/ComponentSettingsTest.cs
Labels: NO-COMMIT-CHECK, improvement

#552 chore: add & reorganize mmd BlendShapes
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
Labels: improvement

#555 fix: Default colliders removed
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug

#554 Check for update
  .docs/build.sh
  .github/workflows/release.yml
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/CheckForUpdate.cs
  Editor/CheckForUpdate.cs.meta
  Editor/Processors/OptimizerPlugin.cs
  Localization/en.po
  Localization/ja.po
Labels: improvement

#556 docs(ja): localize page category
  .docs/content/docs/component-kind/_index.ja.md
  .docs/content/docs/reference/_index.ja.md
  .docs/content/docs/tutorial/_index.ja.md
Labels: documentation, localization

#557 fix: permission of docs build script
  .docs/build.sh
Labels: ci

#561 fix: Freeze BlendShape may break Visame with MergeSkinnedMesh
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/OptimizerSession.cs
  Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Runtime/InternalAutoFreezeMeaninglessBlendShape.cs
Labels: bug

#564 fix(object-mapping): synced layer not proceed correctly
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/ApplyObjectMapping.cs
Labels: bug

#567 Synced layer again & OverrideController
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/ApplyObjectMapping.cs
Labels: NO-CHANGELOG, improvement

#569 Relax limits about normals
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Localization/en.po
  Localization/ja.po
Labels: improvement

#570 chore(migration): ignore instead of just close window
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Migration/PrereleaseStateDetector.cs
Labels: improvement

#572 ci: update gameci and other action
  .github/workflows/gameci-activation.yml
  .github/workflows/gameci.yml
  .github/workflows/prevent-merging-feature.yml
  .github/workflows/release.yml
Labels: ci

#574 「メッシュ」に関する説明を詳しく加筆
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
Labels: documentation, NO-COMMIT-CHECK

#581 fix: Error if MeshRenderer without MeshFilter
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: bug

#584 feat: Satania's Kisetene compatibility
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: improvement

#587 fix: Unused Humanoid Bones disappears
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug

#588 Skip normal check for empty mesh
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
Labels: improvement

#590 docs(changelog): fix typo
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
Labels: documentation

#596 fix: NRE with SMR with None with preview system
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/MeshPreviewController.cs
Labels: bug

#599 fix: BlendShape broken with MergeBone Optimization
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug

#601 fix: Multi frame blendshape broken again
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: bug

#603 Make no-op if no AAO component attached
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MergeBoneProcessor.cs
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/OptimizerPlugin.cs
Labels: improvement

#605 fix: Preview button is not disabled even if mesh is none
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/MeshPreviewController.cs
Labels: bug

#606 chore: refresh error report when playmode exit
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/ErrorReporter/Editor/ErrorReportUI.cs
Labels: improvement

#612 fix: bindpose optimization may break mesh with bones with scale zero
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Math/Matrix3x3.cs
  Editor/Processors/MergeBoneProcessor.cs
Labels: bug

#613 fix: error spam from Preview system
  CHANGELOG-PRERELEASE.md
  Editor/EditModePreview/MeshPreviewController.cs
Labels: bug, SNAPSHOT-ONLY

#615 chore: remove mesh not readable error
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: improvement

#619 feat: add support for VRCQuestTools
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: improvement

#622 fix: AutoFreezeBlendshape will freeze with editor value instead of animated constant
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
Labels: bug

#628 fix: warning with VRCTestMarker
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug

#630 docs: add note about debug features
  README.md
Labels: documentation

#637 refactor: ObjectMapping System
  Editor/AutomaticConfiguration.cs
  Editor/ObjectMapping/AnimationObjectMapper.cs
  Editor/ObjectMapping/ObjectMapping.cs
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Editor/ObjectMapping/ObjectMappingContext.cs
  Editor/Processors/TraceAndOptimize/AnimatorParser.cs
  Editor/Processors/TraceAndOptimize/AnimatorParserDebugWindow.cs
  Editor/Processors/TraceAndOptimize/ModificationsContainers.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Editor/Utils/ComponentOrGameObject.cs
  Editor/Utils/ComponentOrGameObject.cs.meta
  Runtime/TraceAndOptimize.cs
  Test~/AnimatorParser/AnimatorTest.cs
  Test~/ObjectMappingTest.cs
Labels: refactor, improvement

#640 feat: Behaviour activeness in RemoveUnusedObjects
  API-Editor/ComponentInformation.cs
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/GCComponentInfo.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Runtime/TraceAndOptimize.cs
Labels: enhancement

#641 small Speedup
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/SkinnedMeshes/FreezeBlendShapeProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Editor/Utils/MultiDimensionalNativeArray.cs
  Editor/Utils/MultiDimensionalNativeArray.cs.meta
Labels: refactor

#643 Improve log
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/ErrorReporter/Editor/BuildReport.cs
  Internal/ErrorReporter/Editor/BuildReportContext.cs
Labels: improvement

#645 fix: prefab blinks when we see editor of PrefabSafeSet of prefab asset
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs
  Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs.meta
  Internal/PrefabSafeSet/Editor/PrefabSafeSetEditor.cs
Labels: bug

#647 fix: animation clip length can be changed
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/ApplyObjectMapping.cs
Labels: bug

#649 chore: use asmdef name instead of guid for reference
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Internal/ErrorReporter/Editor/com.anatawa12.avatar-optimizer.internal.error-reporter.editor.asmdef
  Internal/ErrorReporter/Runtime/com.anatawa12.avatar-optimizer.internal.error-reporter.runtime.asmdef
  Internal/PrefabSafeSet/Editor/com.anatawa12.avatar-optimizer.internal.prefab-safe-set.editor.asmdef
  Internal/PrefabSafeSet/Runtime/com.anatawa12.avatar-optimizer.internal.prefab-safe-set.asmdef
  Runtime/com.anatawa12.avatar-optimizer.runtime.asmdef
  Test~/Runtime/com.anatawa12.avatar-optimizer.test.runtime.asmdef
  Test~/com.anatawa12.avatar-optimizer.test.asmdef
Labels: refactor

#656 Split ComponentInfo files for VRCSDK and other external libraries
  Editor/APIInternal/ComponentInfoRegistry.cs
  Editor/APIInternal/ComponentInfos.Externals.cs
  Editor/APIInternal/ComponentInfos.Externals.cs.meta
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/APIInternal/ComponentInfos.VRCSDK.cs.meta
  Editor/APIInternal/ComponentInfos.cs
Labels: refactor

#657 refactor: split utils for components of VRCSDK
  Editor/Utils/Utils.VRCSDK.cs
  Editor/Utils/Utils.VRCSDK.cs.meta
  Editor/Utils/Utils.cs
Labels: refactor

#658 chore!: Removed preventing IEditorOnly
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/PreventRemoveAvatarEditorOnly.cs
  Editor/PreventRemoveAvatarEditorOnly.cs.meta
Labels: refactor

#662 Improve multi pass rendering
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/MeshInfo2Holder.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Localization/en.po
  Localization/ja.po
Labels: improvement

#668 Heavy behaviour
  API-Editor/ComponentInformation.cs
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.Externals.cs
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/APIInternal/ComponentInfos.cs
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/GCComponentInfo.cs
Labels: enhancement

#671 Refator Animator Parser
  Editor/AnimatorParsers.meta
  Editor/AnimatorParsers/AnimationParser.cs
  Editor/AnimatorParsers/AnimationParser.cs.meta
  Editor/AnimatorParsers/AnimatorParser.cs
  Editor/AnimatorParsers/AnimatorParser.cs.meta
  Editor/AnimatorParsers/AnimatorParserDebugWindow.cs
  Editor/AnimatorParsers/AnimatorParserDebugWindow.cs.meta
  Editor/AnimatorParsers/ModificationsContainers.cs
  Editor/AnimatorParsers/ModificationsContainers.cs.meta
  Editor/ContextExtensions.cs
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Editor/OptimizerPlugin.cs
  Editor/Processors/ParseAnimator.cs
  Editor/Processors/ParseAnimator.cs.meta
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Editor/Processors/TraceAndOptimize/FindUnusedObjectsProcessor.cs
  Editor/Processors/TraceAndOptimize/GCComponentInfo.cs
  Editor/Processors/TraceAndOptimize/TraceAndOptimizeProcessor.cs
  Test~/AnimatorParser/AnimationFloatPropertyTest.cs
  Test~/AnimatorParser/AnimationFloatPropertyTest.cs.meta
  Test~/AnimatorParser/AnimationPropertyTest.cs
  Test~/AnimatorParser/AnimationTest.cs
  Test~/AnimatorParser/AnimatorTest.cs
Labels: refactor

#673 refactor: ApplySpecialMapping in ComponentInfo
  API-Editor/ComponentInformation.cs
  API-Editor/Internal/InternalParts.cs
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/AnimatorParsers/AnimatorParser.cs
  Editor/ObjectMapping/ObjectMappingContext.cs
  Localization/en.po
  Localization/ja.po
Labels: refactor
