Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-04, with the labels that each got.

#961 Docs improvements
  .docs/CHANGELOG-PRERELEASE.md
  .docs/CHANGELOG.md
  .docs/content/docs/basic-concept/index.ja.md
  .docs/content/docs/basic-concept/index.md
  .docs/content/docs/changelog.ja.md
  .docs/content/docs/changelog.md
  .docs/content/docs/component-kind/_index.ja.md
  .docs/content/docs/component-kind/_index.md
  .docs/content/docs/developers/_index.ja.md
  .docs/content/docs/developers/_index.md
  .docs/content/docs/developers/distributing-prefabs/index.ja.md
  .docs/content/docs/developers/distributing-prefabs/index.md
  .docs/content/docs/faq/index.ja.md
  .docs/content/docs/faq/index.md
  .docs/content/docs/reference/_index.ja.md
  .docs/content/docs/reference/_index.md
  .docs/content/docs/reference/merge-physbone/index.ja.md
  .docs/content/docs/reference/merge-physbone/index.md
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
  .docs/layouts/partials/changelog/CHANGELOG-PRERELEASE.md
  .docs/layouts/partials/changelog/CHANGELOG.md
  .docs/layouts/shortcodes/changelog.html
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Localization/en-us.po
  Localization/ja-jp.po
Labels: documentation

#974 ci: tests not ran
  .github/workflows/gameci.yml
  Editor/ConfigureClampBlendShape.cs
Labels: ci

#976 [RFC] Public API
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
  README.md
  Runtime/API.meta
  Runtime/API/PrefabSafeSetAccessor.cs
  Runtime/API/PrefabSafeSetAccessor.cs.meta
  Runtime/AvatarGlobalComponent.cs
  Runtime/EditSkinnedMeshComponent.cs
  Runtime/MergeSkinnedMesh.cs
  Runtime/RemoveMeshByBlendShape.cs
  Runtime/RemoveMeshInBox.cs
  Runtime/TraceAndOptimize.cs
  Test~/Basic/PublicApiCheck.cs
Labels: enhancement

#990 fix: bounds broken with updateWhenOffscreen = true
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
Labels: bug

#994 feat: remove animations about missing GameObject
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ObjectMapping/AnimationObjectMapper.cs
  Test~/Basic/ObjectMappingTest.cs
Labels: enhancement

#998 feat: Remove mesh by mask
  .docs/content/docs/reference/remove-mesh-by-mask/component.png
  .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-mask/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ComponentValidation.cs
  Editor/EditModePreview/RemoveMeshPreviewController.cs
  Editor/EditSkinnedMeshComponentUtil.cs
  Editor/Inspector/RemoveMeshByMaskEditor.cs
  Editor/Inspector/RemoveMeshByMaskEditor.cs.meta
  Editor/Processors/SkinnedMeshes/RemoveMeshByMaskProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByMaskProcessor.cs.meta
  Localization/en-us.po
  Localization/ja-jp.po
  Runtime/EditSkinnedMeshComponent.cs
  Runtime/MergeSkinnedMesh.cs
  Runtime/RemoveMeshByMask.cs
  Runtime/RemoveMeshByMask.cs.meta
  Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue989.meta
Labels: enhancement

#1007 feat(T&O): remove empty submesh
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditSkinnedMeshComponentUtil.cs
  Editor/OptimizerPlugin.cs
  Editor/Processors/SkinnedMeshes/EditSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveEmptySubMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/RemoveEmptySubMeshProcessor.cs.meta
  Editor/Processors/TraceAndOptimize/AddRemoveEmptySubMesh.cs
  Editor/Processors/TraceAndOptimize/AddRemoveEmptySubmesh.cs.meta
  Internal/TraceAndOptimizeBase/TraceAndOptimizeProcessor.cs
  Runtime/TraceAndOptimize.cs
Labels: bug

#1011 fix: error with duplicated animation curve
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/AnimatorParserV2/AnimationParser.cs
  Editor/AnimatorParserV2/NodeContainer.cs
Labels: bug

#1022 ci: update changelog url on release action
  .github/workflows/release.yml
Labels: NO-CHANGELOG

#1023 ci: unchanged package.json is uploaded to release
  .github/workflows/release.yml
Labels: NO-CHANGELOG

#1031 docs(trace-and-optimize): fix about Merge Skinned Mesh
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
Labels: documentation

#1032 docs(make-your-components-compatible-with-aao): add Asset Description in How to improve the compatibility
  .docs/content/docs/developers/asset-description/index.en.md
  .docs/content/docs/developers/asset-description/index.ja.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
Labels: documentation

#1033 chore: start stable releases of 1.7.0
  package.json
Labels: NO-CHANGELOG
