Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-10, with the labels that each got.

#1237 fix: CS8632 on released assets
  .csc.rsp.nullsafe
  CHANGELOG-PRERELEASE.md
Labels: SNAPSHOT-ONLY

#1249 test: exclude test code from coverage
  .github/workflows/gameci.yml
Labels: ci

#1251 fix: compile error with merge conflict
  Editor/Processors/SkinnedMeshes/RenameBlendShapeProcessor.cs
Labels: NO-CHANGELOG

#1257 feat: invert option for RemoveMeshInBox
  .docs/Unity/Anon.unity
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.md
  .docs/content/docs/reference/remove-mesh-by-box/after.png
  .docs/content/docs/reference/remove-mesh-by-box/before.png
  .docs/content/docs/reference/remove-mesh-by-box/component.png
  .docs/content/docs/reference/remove-mesh-by-box/gizmo.png
  .docs/content/docs/reference/remove-mesh-by-box/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-box/index.md
  .docs/content/docs/reference/remove-mesh-in-box/after.png
  .docs/content/docs/reference/remove-mesh-in-box/before.png
  .docs/content/docs/reference/remove-mesh-in-box/component.png
  .docs/content/docs/reference/remove-mesh-in-box/gizmo.png
  .docs/content/docs/reference/remove-mesh-in-box/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/MeshRemovalProviderImpl.cs
  Editor/EditModePreview/RemoveMeshInBoxRenderFilter.cs
  Editor/Inspector/RemoveMeshInBoxEditor.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshInBoxProcessor.cs
  Localization/en-us.po
  Localization/ja-jp.po
  Runtime/RemoveMeshInBox.cs
Labels: enhancement

#1265 docs(ja/en): chore docs
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/rename-blendshape/index.ja.md
  .docs/content/docs/reference/rename-blendshape/index.md
Labels: documentation

#1273 Save material info and call infromation once
  API-Editor/ShaderInformation.cs
  Editor/APIInternal/ShaderInformation.Liltoon.cs
  Editor/OptimizerPlugin.cs
  Editor/Processors/ShaderMaterialInformation.cs
  Editor/Processors/ShaderMaterialInformation.cs.meta
  Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
  Test~/Basic/OptimizeTextureTest.cs
Labels: NO-CHANGELOG

#1041 Feat material unused property remove
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/OptimizerPlugin.cs
  Editor/Processors/TraceAndOptimize/RemoveUnusedMaterialProperties.cs
  Editor/Processors/TraceAndOptimize/RemoveUnusedMaterialProperties.cs.meta
  Internal/TraceAndOptimizeBase/TraceAndOptimizeProcessor.cs
  Runtime/TraceAndOptimize.cs
Labels: enhancement

#1315 chore(ja/en): l10n follow 1296
  Localization/en-us.po
  Localization/ja-jp.po
Labels: localization
