Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-05, with the labels that each got.

#1036 docs(ja): remove trailing backslash followed by a hard-break
  .docs/content/docs/basic-concept/index.ja.md
Labels: documentation

#1050 fix: entry exit to blendtree with none broken
  Assets/Empty.anim
  Assets/Empty.anim.meta
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
  Internal/Utils/CachedGuidLoader.cs
  Internal/Utils/CachedGuidLoader.cs.meta
Labels: bug

#1044 feat: implement mask texture editor
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/MeshPreviewController.cs
  Editor/EditModePreview/RemoveMeshPreviewController.cs
  Editor/Inspector/RemoveMeshByMaskEditor.cs
  Editor/MaskTextureEditor.meta
  Editor/MaskTextureEditor/Inspector.cs
  Editor/MaskTextureEditor/Inspector.cs.meta
  Editor/MaskTextureEditor/Shaders.meta
  Editor/MaskTextureEditor/Shaders/Fill.shader
  Editor/MaskTextureEditor/Shaders/Fill.shader.meta
  Editor/MaskTextureEditor/Shaders/Inverse.shader
  Editor/MaskTextureEditor/Shaders/Inverse.shader.meta
  Editor/MaskTextureEditor/Shaders/Paint.shader
  Editor/MaskTextureEditor/Shaders/Paint.shader.meta
  Editor/MaskTextureEditor/TexturePainter.cs
  Editor/MaskTextureEditor/TexturePainter.cs.meta
  Editor/MaskTextureEditor/TextureUndoStack.cs
  Editor/MaskTextureEditor/TextureUndoStack.cs.meta
  Editor/MaskTextureEditor/UvMapDrawer.cs
  Editor/MaskTextureEditor/UvMapDrawer.cs.meta
  Editor/MaskTextureEditor/Window.cs
  Editor/MaskTextureEditor/Window.cs.meta
  Localization/en-us.po
  Localization/ja-jp.po
Labels: improvement

#1054 fix: particle system with bone-skinned skinned mesh renderer will break
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/ComponentDependencyCollector.cs
Labels: bug

#1051 Mask texture editor
  .docs/content/docs/reference/remove-mesh-by-mask/component.png
  .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-mask/index.md
  .docs/content/docs/reference/remove-mesh-by-mask/mask-editor.png
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/MeshPreviewController.cs
  Editor/EditModePreview/RemoveMeshPreviewController.cs
  Editor/Inspector/RemoveMeshByMaskEditor.cs
  Editor/MaskTextureEditor.meta
  Editor/MaskTextureEditor/Inspector.cs
  Editor/MaskTextureEditor/Inspector.cs.meta
  Editor/MaskTextureEditor/Shaders.meta
  Editor/MaskTextureEditor/Shaders/Fill.shader
  Editor/MaskTextureEditor/Shaders/Fill.shader.meta
  Editor/MaskTextureEditor/Shaders/Inverse.shader
  Editor/MaskTextureEditor/Shaders/Inverse.shader.meta
  Editor/MaskTextureEditor/Shaders/Paint.shader
  Editor/MaskTextureEditor/Shaders/Paint.shader.meta
  Editor/MaskTextureEditor/TexturePainter.cs
  Editor/MaskTextureEditor/TexturePainter.cs.meta
  Editor/MaskTextureEditor/TextureUndoStack.cs
  Editor/MaskTextureEditor/TextureUndoStack.cs.meta
  Editor/MaskTextureEditor/UvMapDrawer.cs
  Editor/MaskTextureEditor/UvMapDrawer.cs.meta
  Editor/MaskTextureEditor/Window.cs
  Editor/MaskTextureEditor/Window.cs.meta
  Localization/en-us.po
  Localization/ja-jp.po
Labels: improvement

#1055 Add Simplified Chinese translation
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/Localization/Editor/AAOL10N.cs
  Localization/zh-cn.po
Labels: NO-COMMIT-CHECK

#1059 fix: missing meta file for zh-cn
  Localization/zh-cn.po.meta
Labels: NO-CHANGELOG

#1062 fix: WD=off behavior broken
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
  Internal/AnimatorOptimizer/MergeBlendTreeLayer.cs
  Internal/AnimatorOptimizer/Wrappers.cs
  Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue989/FX_Without_2.converted.controller
  Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue989/FX_Without_2_With_Same_Motion.converted.controller
  Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue989/FX_Without_3.converted.controller
  Test~/AnimatorOptimizer/EntryExitToBlendTree/Issue989/FX_Without_3_With_Same_Motion.converted.controller
  Test~/AnimatorOptimizer/MergeBlendTreeLayer/ConvertibleSimple.converted.controller
  Test~/AnimatorOptimizer/MergeBlendTreeLayer/ConvertibleSimple.meaningless-removed.controller
Labels: bug

#1063 fix: size of _texCoordStatus is not enough
  Internal/MeshInfo2/MeshInfo2.cs
Labels: NO-CHANGELOG
