Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-02, with the labels that each got.

#847 Easy way to register meaningless components
  .docs/content/docs/developers/asset-description/asset-description-inspector.png
  .docs/content/docs/developers/asset-description/index.en.md
  .docs/content/docs/developers/asset-description/index.ja.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfoRegistry.cs
  Editor/APIInternal/ComponentInfos.Externals.cs
  Editor/AssetDescription.cs
  Editor/AssetDescription.cs.meta
  Editor/CheckForUpdate.cs
  Editor/OptimizerPlugin.cs
  ExternalDescriptions.meta
  ExternalDescriptions/SataniaKisetene.asset
  ExternalDescriptions/SataniaKisetene.asset.meta
  Localization/en.po
  Localization/ja.po
Labels: enhancement

#902 chore: remove redundant whitespace from translation
  Localization/ja.po
Labels: documentation, NO-COMMIT-CHECK

#769 Warning for material property animation
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ObjectMapping/ObjectMappingBuilder.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/ShaderKnowledge.cs
  Editor/ShaderKnowledge.cs.meta
  Localization/en.po
  Localization/ja.po
Labels: enhancement

#905 fix: VRCImposterSettings is missing in VRCSDK 3.2.x
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
Labels: bug

#908 docs: Add about `Optimize PhysBone Settings`
  .docs/content/docs/reference/trace-and-optimize/component.png
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
Labels: documentation

#910 docs(ja): fix typo
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
Labels: documentation
