Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-08, with the labels that each got.

#1124 chore: add more description for MergeSMR
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  Localization/en-us.po
  Localization/ja-jp.po
Labels: documentation, localization

#1139 chore: mention initially not configured viseme / eyelids
  Localization/en-us.po
  Localization/ja-jp.po
Labels: NO-CHANGELOG

#1149 chore: remove 2019 CI
  .github/workflows/gameci.yml
Labels: NO-CHANGELOG

#1164 fix: link to asset description on the inspector is broken
  Editor/AssetDescription.cs
Labels: NO-CHANGELOG

#1162 feat: add many hints to warnings
  Localization/en-us.po
  Localization/ja-jp.po
Labels: localization

#1163 docs: mention non-destructive in basic-concept
  .docs/content/docs/basic-concept/index.ja.md
  .docs/content/docs/basic-concept/index.md
Labels: documentation

#1167 chore(zh-hant): update localization
  Localization/zh-hant.po
Labels: localization

#1165 refactor: use generics in PrefabSafeSet
  Internal/PrefabSafeSet/Editor/BasicTypeEditors.cs
  Internal/PrefabSafeSet/Editor/OnBeforeSerializeImpl.cs
  Internal/PrefabSafeSet/Editor/PrefabSafeSetEditor.cs
  Internal/PrefabSafeSet/Runtime/PrefabSafeSet.cs
  Internal/PrefabSafeSet/Runtime/PrefabSafeSetTestComponent.cs
  Internal/PrefabSafeSet/Runtime/generate.ts
  Internal/PrefabSafeSet/Runtime/generate.ts.meta
  Internal/PrefabSafeSet/Runtime/generated.cs
  Internal/PrefabSafeSet/Runtime/generated.cs.meta
  Runtime/FreezeBlendShape.cs
  Runtime/MakeChildren.cs
  Runtime/MergePhysBone.cs
  Runtime/MergeSkinnedMesh.cs
  Runtime/RemoveMeshByBlendShape.cs
  Test~/Runtime/PrefabSafeSetComponent.cs
Labels: refactor

#1168 Merge 1.7.12
  .docs/build-latest-txt.mjs
  .docs/build.sh
  .docs/content/docs/basic-concept/index.ja.md
  .docs/content/docs/basic-concept/index.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
  API-Editor/ComponentInformation.cs
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.FinalIK.cs
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/AssetDescription.cs
  Editor/CheckForUpdate.cs
  Editor/CheckForUpdate.cs.meta
  Editor/CheckForUpdate.meta
  Editor/CheckForUpdate/CheckForUpdate.cs
  Editor/CheckForUpdate/CheckForUpdate.cs.meta
  Editor/CheckForUpdate/CheckForUpdateContext.cs
  Editor/CheckForUpdate/CheckForUpdateContext.cs.meta
  Editor/CheckForUpdate/Latest2TextFile.cs
  Editor/CheckForUpdate/Latest2TextFile.cs.meta
  Editor/CheckForUpdate/MenuItems.cs
  Editor/CheckForUpdate/MenuItems.cs.meta
  Editor/CheckForUpdate/UnityVersion.cs
  Editor/CheckForUpdate/UnityVersion.cs.meta
  Editor/CheckForUpdate/Version.cs
  Editor/CheckForUpdate/Version.cs.meta
  Editor/Inspector/MergePhysBoneEditor.cs
  Editor/OptimizerPlugin.cs
  Editor/Processors/MergePhysBoneProcessor.cs
  Localization/en-us.po
  Localization/ja-jp.po
  Localization/zh-cn.po
  Localization/zh-hant.po
  Test~/Basic/CheckForUpdateLatest2TextFile.cs
  Test~/Basic/CheckForUpdateLatest2TextFile.cs.meta
  Test~/Basic/CheckForUpdateVersion.cs
  Test~/Basic/CheckForUpdateVersion.cs.meta
Labels: NO-CHANGELOG
