Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-11, with the labels that each got.

#1323 feat: add external description for nadeXnade
  ExternalDescriptions/nadeXnade.asset
  ExternalDescriptions/nadeXnade.asset.meta
Labels: NO-CHANGELOG

#1325 perf: optimize InternalAutoFreezeMeaninglessBlendShapeProcessor
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/SkinnedMeshes/InternalAutoFreezeMeaninglessBlendShapeProcessor.cs
Labels: NO-COMMIT-CHECK

#1340 Error with nested merge skinned mesh
  CHANGELOG-PRERELEASE.md
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Runtime/assembly-info.cs
  Test~/Basic/MergeSkinnedMeshTest.cs
  Test~/Utils/TestUtils.cs
Labels: SNAPSHOT-ONLY

#1342 fix: Unpacking prefab might look like some data lost in PrefabSafeUniqueCollection
  CHANGELOG-PRERELEASE.md
  Internal/PrefabSafeSet/Editor/UniqueCollection/BaseEditorUtil.PrefabModificationBase.cs
  Internal/PrefabSafeSet/Runtime/PrefabSafeSetTestComponent.cs
  Runtime/FreezeBlendShape.cs
  Runtime/MakeChildren.cs
  Runtime/MergePhysBone.cs
  Runtime/MergeSkinnedMesh.cs
  Runtime/RemoveMeshByBlendShape.cs
  Runtime/RenameBlendShape.cs
  Test~/PrefabSafeSet/PSSTestUtil.cs
  Test~/Runtime/PrefabSafeSetComponent.cs
Labels: SNAPSHOT-ONLY

#1335 Docs
  .docs/content/_index.ja.md
  .docs/content/_index.md
  .docs/content/docs/basic-concept/index.ja.md
  .docs/content/docs/basic-concept/index.md
  .docs/content/docs/developers/asset-description/index.en.md
  .docs/content/docs/developers/asset-description/index.ja.md
  .docs/content/docs/developers/component-api/index.ja.md
  .docs/content/docs/developers/component-api/index.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
  .docs/content/docs/faq/index.ja.md
  .docs/content/docs/faq/index.md
  .docs/content/docs/reference/freeze-blendshape/index.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/remove-mesh-by-mask/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-mask/index.md
  .docs/content/docs/reference/rename-blendshape/index.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
  README.md
Labels: documentation

#1352 Bump NDMF to 1.6.0
  Editor/ObjectMapping/ObjectMappingContext.cs
  package.json
Labels: NO-CHANGELOG

#1355 build: ready for stable release
  package.json
Labels: NO-CHANGELOG
