Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-09, with the labels that each got.

#1171 docs: Convert AnyState to Entry-Exit
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
Labels: documentation

#1186 ci: run ci with graphics (remove -nographics)
  .github/workflows/gameci.yml
Labels: ci

#1174 docs(scss): Create a style
  .docs/assets/_custom.scss
Labels: documentation

#1190 chore: allow 1.8 beta
  package.json
Labels: NO-CHANGELOG

#1191 ci: add ndmf prereleases repository
  .github/workflows/gameci.yml
Labels: ci

#1199 fix: NRE with newly created VRCAnimatorPlayAudio
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ObjectMapping/ObjectMappingContext.cs
Labels: bug

#1204 Improve Shader Knowlage
  API-Editor/ShaderInformation.cs
  Editor/APIInternal/ShaderInformation.Liltoon.cs
  Editor/Processors/TraceAndOptimize/OptimizeTexture.cs
Labels: NO-CHANGELOG
