Repository anatawa12/AvatarOptimizer, pull requests merged in 2024-03, with the labels that each got.

#620 docs: some improvement
  .booth/README.md
  .docs/content/_index.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.ja.md
  .docs/content/docs/component-kind/edit-skinned-mesh-components/index.md
  .docs/content/docs/developers/asset-description/index.en.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.ja.md
  .docs/content/docs/developers/make-your-components-compatible-with-aao/index.md
  .docs/content/docs/reference/freeze-blendshape/index.ja.md
  .docs/content/docs/reference/freeze-blendshape/index.md
  .docs/content/docs/reference/merge-bone/index.ja.md
  .docs/content/docs/reference/merge-bone/index.md
  .docs/content/docs/reference/merge-physbone/index.ja.md
  .docs/content/docs/reference/merge-physbone/index.md
  .docs/content/docs/reference/merge-skinned-mesh/index.ja.md
  .docs/content/docs/reference/merge-skinned-mesh/index.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.ja.md
  .docs/content/docs/reference/remove-mesh-by-blendshape/index.md
  .docs/content/docs/reference/remove-zero-sized-polygon/index.md
  .docs/content/docs/reference/trace-and-optimize/index.ja.md
  .docs/content/docs/reference/trace-and-optimize/index.md
  .docs/content/docs/tutorial/basic-usage/index.ja.md
  .docs/content/docs/tutorial/basic-usage/index.md
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/ComponentValidation.cs
  Editor/EditModePreview/BlendShapePreviewContext.cs
  Editor/EditModePreview/RemoveMeshByBlendShapePreviewContext.cs
  Editor/Inspector/AvatarGlobalComponentEditorBase.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Processors/SkinnedMeshes/MeshInfo2.cs
  Editor/Processors/SkinnedMeshes/RemoveMeshByBlendShapeProcessor.cs
  Editor/Processors/TraceAndOptimize/AutoFreezeBlendShape.cs
  Localization/en.po
  Localization/ja.po
Labels: documentation, localization

#926 VRCSDK 3.5.2 beta.1 support
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/APIInternal/ComponentInfos.VRCSDK.cs
  Editor/ObjectMapping/ObjectMappingContext.cs
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Test~/ComponentWhitelistTest.cs
Labels: bug

#928 Refactor
  Editor/AnimatorController/ACUtils.GetControllerAndOverrides.cs
  Editor/AnimatorController/ACUtils.VRCSDKWeightChanges.cs
  Editor/AnimatorController/ACUtils.cs
  Editor/AnimatorParserV2/AnimationParser.cs
  Editor/AnimatorParserV2/AnimatorControllerPropModNode.cs
  Editor/AnimatorParserV2/AnimatorParser.cs
  Editor/AnimatorParserV2/PropModNode.cs
  Editor/AnimatorParserV2/Utilities.cs
  Editor/Inspector/MergeToonLitMaterialEditor.cs
  Editor/Processors/SkinnedMeshes/MergeToonLitMaterialProcessor.cs
  Editor/Utils/Assets.cs
  Editor/Utils/Assets.cs.meta
  Editor/Utils/VRCSDKUtils.cs
  Editor/Utils/VRCSDKUtils.cs.meta
  Editor/com.anatawa12.avatar-optimizer.editor.asmdef
  Internal/Utils.meta
  Internal/Utils/Utils.BoundsCornersEnumerable.cs
  Internal/Utils/Utils.BoundsCornersEnumerable.cs.meta
  Internal/Utils/Utils.CastDic.cs
  Internal/Utils/Utils.CastDic.cs.meta
  Internal/Utils/Utils.CopyDataFrom.cs
  Internal/Utils/Utils.CopyDataFrom.cs.meta
  Internal/Utils/Utils.Float.cs
  Internal/Utils/Utils.Float.cs.meta
  Internal/Utils/Utils.GetHashCode2.cs
  Internal/Utils/Utils.GetHashCode2.cs.meta
  Internal/Utils/Utils.ObjectReferencePropertiesEnumerable.cs
  Internal/Utils/Utils.ObjectReferencePropertiesEnumerable.cs.meta
  Internal/Utils/Utils.TransformDirectChildrenEnumerable.cs
  Internal/Utils/Utils.TransformDirectChildrenEnumerable.cs.meta
  Internal/Utils/Utils.TransformParentEnumerable.cs
  Internal/Utils/Utils.TransformParentEnumerable.cs.meta
  Internal/Utils/Utils.cs
  Internal/Utils/Utils.cs.meta
  Internal/Utils/com.anatawa12.avatar-optimizer.internal.utils.asmdef
  Internal/Utils/com.anatawa12.avatar-optimizer.internal.utils.asmdef.meta
  Internal/Utils/csc.rsp
  Internal/Utils/csc.rsp.meta
  Test~/com.anatawa12.avatar-optimizer.test.asmdef
Labels: refactor

#931 CI with unity 2022
  .github/workflows/gameci.yml
Labels: ci

#936 pick 2022 ci
  .github/workflows/gameci.yml
Labels: ci

#937 ci: use actions-github-app to publish
  .github/workflows/release.yml
Labels: ci

#929 docs(contributing): add about localization changes
  CONTRIBUTING.md
Labels: documentation

#941 chore(animator-parser): rewrite in C# 9 and fix around solo and mute
  Internal/AnimatorOptimizer/AnimOptPassBase.cs
  Internal/AnimatorOptimizer/EntryExitToBlendTree.cs
  Internal/AnimatorOptimizer/KnownAnimatorValues.cs
  Internal/AnimatorOptimizer/MergeDirectBlendTree.cs
  Internal/AnimatorOptimizer/Wrappers.cs
  Internal/AnimatorOptimizer/csc.rsp
  Internal/AnimatorOptimizer/csc.rsp.meta
Labels: refactor

#945 chore(merge-physbone): make endpointPosition copy by default instead of clear
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Runtime/MergePhysBone.cs
Labels: enhancement

#948 Merge Skinned Mesh activeness animation warning improvements
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/AnimatorParserV2/PropModNode.cs
  Editor/Processors/SkinnedMeshes/MergeSkinnedMeshProcessor.cs
  Editor/Utils/AnimationLocation.cs
Labels: enhancement, improvement

#956 Fix Editmode preview
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/EditModePreview/MeshPreviewController.cs
Labels: bug

#965 chore: use locale code with region code
  Internal/Localization/Editor/AAOL10N.cs
  Localization/en-us.po
  Localization/en-us.po.meta
  Localization/ja-jp.po
  Localization/ja-jp.po.meta
Labels: NO-CHANGELOG

#966 chore: start beta releases of 1.7.0
  package.json
Labels: NO-CHANGELOG

#972 fix(auto merge smr): Activeness of renderer object
  .editorconfig
  CHANGELOG-PRERELEASE.md
  CHANGELOG.md
  Editor/Processors/TraceAndOptimize/AutoMergeSkinnedMesh.cs
  Internal/Utils/EqualsHashSet.cs
  Internal/Utils/EqualsHashSet.cs.meta
  Internal/Utils/Utils.cs
Labels: bug
